#### DEFAULT CONFIG
[ui]
desc = "Click one of the buttons below to play a sound!"
heading = "Sirenus Soundboard"
title = "Sirenus"

[app]
host = "0.0.0.0"
port = 5000
sample_rate = 44100
sound_dir = 'static/sounds/'
